<!DOCTYPE sql-queries [
<!ELEMENT sql-queries (sql-query)*>
<!ELEMENT sql-query (#PCDATA)>
<!ATTLIST sql-query id CDATA #REQUIRED>
]>
<sql-queries>
    <sql-query id="checkemail">
        <![CDATA[SELECT * FROM user_tbl WHERE email =? order by id desc]]>
    </sql-query>
    <sql-query id="registration">
        <![CDATA[INSERT INTO user_tbl(date_created,name,email,password,password_salt,verification_key,active) values(?,?,?,?,?,?,'yes')]]>
    </sql-query>
    <sql-query id="getUserEmailForMentions">
        <![CDATA[select ut.email,up.timezone_id
        from entity_tbl et
        inner join user_tbl ut on ut.id=et.entity_id
        inner join user_profile_tbl up
        on up.user_id=ut.id
        where et.entity_id=? and entity_type='user'
        union all
        SELECT ut.email,up.timezone_id FROM user_tbl ut inner join user_profile_tbl up
        on ut.id=up.user_id
        inner join charity_admin_tbl cat ON ut.id = cat.user_id
        inner join code_tbl ct ON (cat.charity_id=ct.charity_id and default_value=1)
        WHERE ct.id=?
        union all
        SELECT ut.email,up.timezone_id FROM user_tbl ut inner join user_profile_tbl up
        on ut.id=up.user_id
        inner join charity_admin_tbl cat ON ut.id = cat.user_id
        WHERE cat.charity_id = ? and default_value=1
        union all
        select ut.email,up.timeZone_id from user_tbl ut
        inner join user_profile_tbl up on up.user_id=ut.id
        inner join code_tbl ct on ct.user_id=ut.id where ct.id=?
        ]]>
    </sql-query>
    <sql-query id="getOriginalmeg">
        <![CDATA[select sut.*,upt.profile_pic_url,ut.name,ut.id,ut.email,et.entity_type,et.slug,
        COALESCE(uparent.name,oparent.title ) as parent_creator_name,
        COALESCE(upparent.profile_pic_url,oparent.profile_pic_url) as parent_creator_pic,
        COALESCE(uparent.id,cparent.id) as parent_creator_id,
        COALESCE(etparent.entity_type) as parent_type,
        mt.metadata as metadata,
        mt.code_json as code_tmpl
        from status_update_tbl sut
        inner Join entity_tbl et on et.id=sut.entity_id
        inner join user_tbl ut on ut.id=et.entity_id and et.entity_type ='user'
        inner join user_profile_tbl upt on upt.user_id=ut.id
        left outer join metadata_tbl mt on mt.post_id = sut.id
        left outer join entity_tbl etparent ON sut.original_entity_id = etparent.id and sut.status_type='share' and sut.date_deleted is null
        left outer join user_tbl uparent ON uparent.id = etparent.entity_id and etparent.entity_type ='user'
        left outer join user_profile_tbl upparent ON uparent.id = upparent.user_id
        left outer join charity_tbl cparent ON cparent.id=etparent.entity_id and etparent.entity_type ='charity'
        left outer join organization_tbl oparent ON oparent.id = cparent.organization_id
        where sut.id=?
        union all
        select sut.*,o.profile_pic_url,o.title,c.id,ut.email,et.entity_type,et.slug,
        COALESCE(uparent.name,oparent.title ) as parent_creator_name,
        COALESCE(upparent.profile_pic_url,oparent.profile_pic_url) as parent_creator_pic,
        COALESCE(uparent.id,cparent.id) as parent_creator_id,
        COALESCE(etparent.entity_type) as parent_type,
        mt.metadata as metadata,
        mt.code_json as code_tmpl
        from status_update_tbl sut
        inner Join entity_tbl et on et.id=sut.entity_id
        inner Join charity_tbl c ON c.id = et.entity_id and et.entity_type ='charity'
        inner Join charity_admin_tbl cat ON cat.charity_id = c.id
        inner Join user_tbl ut ON ut.id = cat.user_id
        inner Join organization_tbl o ON o.id = c.organization_id
        left outer join metadata_tbl mt on mt.post_id = sut.id
        left outer join entity_tbl etparent ON sut.original_entity_id = etparent.id and sut.status_type='share' and sut.date_deleted is null
        left outer join user_tbl uparent ON uparent.id = etparent.entity_id and etparent.entity_type ='user'
        left outer join user_profile_tbl upparent ON uparent.id = upparent.user_id
        left outer join charity_tbl cparent ON cparent.id=etparent.entity_id and etparent.entity_type ='charity'
        left outer join organization_tbl oparent ON oparent.id = cparent.organization_id
        where sut.id=?]]>
    </sql-query>
    <sql-query id="updateDonorDetails">
        <![CDATA[UPDATE user_tbl SET name=?,password=?,password_salt=?,verification_key=?,active='yes' WHERE id=?]]>
    </sql-query>
    <sql-query id="checkemailact">
        <![CDATA[SELECT * FROM user_tbl WHERE id =?]]>
    </sql-query>
    <sql-query id="checkemailactteam">
        <![CDATA[SELECT *,(SELECT count(*) FROM team_invitees_tbl WHERE team_id=?) AS invitations_count  FROM user_tbl WHERE id =?]]>
    </sql-query>
    <sql-query id="checkAdminEmail">
        <![CDATA[SELECT * FROM user_tbl WHERE email =?]]>
    </sql-query>
    <sql-query id="checkAdminEmailInCharity">
        <![CDATA[SELECT * FROM charity_admin_tbl WHERE charity_id =? and user_id=? and date_deleted is null]]>
    </sql-query>
    <sql-query id="login_sql">
        <![CDATA[SELECT u.*,ca.*,up.*, u.id as 'user_id',
        et.id as entity_id ,et.slug as userSlug,
        cct.country_code,
         cunt.currency_code,
         cunt.currency_symbol
            FROM user_tbl u
            INNER JOIN user_profile_tbl up ON up.user_id = u.id
            LEFT JOIN charity_admin_tbl ca ON ca.user_id = u.id
            left outer join countries_tbl cct on cct.id= up.country
            left outer join countries_currency cunt on cunt.country_id = up.country
            Inner join entity_tbl et on et.entity_id = u.id
            WHERE u.email =? and password=? and et.entity_type = 'user']]>
    </sql-query>
    <sql-query id="autoLoginSql">
        <![CDATA[SELECT u.*,ca.*,up.*, u.id as 'user_id', et.id as entity_id ,et.slug as userSlug FROM user_tbl u INNER JOIN user_profile_tbl up ON up.user_id = u.id
        LEFT JOIN charity_admin_tbl ca ON ca.user_id = u.id
        Inner join entity_tbl et on et.entity_id = u.id
        WHERE u.id =? and et.entity_type = 'user']]>
    </sql-query>
    <sql-query id="donor_default_login">
        <![CDATA[SELECT u.*,ca.*,up.*, u.id as 'user_id', et.id as entity_id ,et.slug as userSlug FROM user_tbl u
        inner join user_profile_tbl up ON up.user_id = u.id
        left outer join charity_admin_tbl ca ON ca.user_id = u.id
        inner join entity_tbl et on et.entity_id = u.id
        WHERE u.id=? and et.entity_type = 'user']]>
    </sql-query>
    <sql-query id="login_sqlcheck">
        <![CDATA[SELECT * FROM user_tbl WHERE email =? order by id asc]]>
    </sql-query>
    <sql-query id="postFeed">
        <![CDATA[INSERT INTO status_update_tbl (in_reply_id,entity_id,date_posted,ip_address,hostname,city,state,content,status_type,image_url,headline,original_entity_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)]]>
    </sql-query>
    <sql-query id="deleteFeed">
        <![CDATA[UPDATE status_update_tbl SET date_deleted=now() WHERE id=? or (in_reply_id=? and status_type!='share')]]>
    </sql-query>
    <sql-query id="getDeleteFeeds">
        <![CDATA[select entity_id,status_type from status_update_tbl WHERE id=?]]>
    </sql-query>
    <sql-query id="feedList">
        <![CDATA[SELECT  sut.*,sut.id 'post_id', sut.date_posted 'date_post', et.id 'entity_id', et.entity_id 'charity_id',
        ct.name_tmp 'charity_name',ot.profile_pic_url 'profile_pic', sut.content 'charity_feed', sut.image_url 'image'
        FROM status_update_tbl sut
        INNER JOIN entity_tbl et ON sut.entity_id = et.id
        INNER JOIN charity_tbl ct ON et.entity_id = ct.id and et.entity_type='charity'
        INNER JOIN organization_tbl ot ON ct.organization_id = ot.id
        WHERE et.entity_id = ? and sut.status_type='post' and sut.date_deleted is null
        ORDER BY sut.date_posted DESC
        LIMIT 10 OFFSET ?]]>
    </sql-query>
    <sql-query id="teamdata">
        <![CDATA[select tt.*,ut.name as team_creator_name,et.slug as team_slug,ut.email as creator_email,ct.code_text as main_campaign_slug,ct.title as main_campaign_name from teams_tbl tt inner join user_tbl ut
on ut.id=tt.tc_user_id and tt.id=?
left outer join code_tbl ct on ct.id=tt.code_id
inner join entity_tbl et on et.entity_id=tt.id and et.entity_type='team';]]>
    </sql-query>
    <sql-query id="denyTeamRecord">
        <![CDATA[delete from teams_tbl where id=?]]>
    </sql-query>
    <sql-query id="getStatusUpdate">
        <![CDATA[update teams_tbl set status="published",approved_by=?,approved_date=? where id=?]]>
    </sql-query>
    <sql-query id="getTeamApprove">
        <![CDATA[select * from team_invitees_tbl where team_id=?]]>
    </sql-query>
    <sql-query id="getTeamUser">
        <![CDATA[select * from user_tbl where id in (?)]]>
    </sql-query>
    <sql-query id="retriveCharityFollowers">
        <![CDATA[SELECT entity_tbl.entity_id as charity_id,
        entity_tbl.id as entity_id,
        follow_tbl.user_id as url,
        user_tbl.name as display_name,
        user_tbl.id as user_id,
        user_profile_tbl.profile_pic_thumb_url as profile_pic_thumb_url,
        user_profile_tbl.city as city,
        user_profile_tbl.state as state,
        user_profile_tbl.about_me as description
        FROM  entity_tbl, follow_tbl, user_tbl, user_profile_tbl
        WHERE entity_tbl.entity_id=?
        AND entity_tbl.entity_type='charity'
        AND follow_tbl.entity_id=entity_tbl.id
        AND user_tbl.id=follow_tbl.user_id
        AND user_profile_tbl.user_id=user_tbl.id
        ORDER BY user_tbl.name ASC]]>
    </sql-query>
    <sql-query id="getCharityAdminUserName">
        <![CDATA[SELECT name,id AS admin_id FROM user_tbl WHERE id=?]]>
    </sql-query>
    <!-- charityDetails and charityObj data used in causeportal -->
    <sql-query id="getCharityAdminUserPermissions">
        <![CDATA[SELECT charity_admin_tbl.id as id,
        charity_admin_tbl.can_post as can_post,
        charity_admin_tbl.can_update_financial as can_update_financial,
        charity_admin_tbl.can_request_withdrawal as can_request_withdrawal,
        charity_admin_tbl.can_view_reports as can_view_reports,
        charity_admin_tbl.can_code as can_code,
        charity_admin_tbl.can_manage_followers as can_manage_followers,
        charity_admin_tbl.can_admin as can_admin,
        charity_tbl.organization_id as organization_id,
        charity_tbl.charity_from as charity_from,
        charity_tbl.wepay_account_state as wepay_account_state,
        charity_tbl.country as country,
        charity_tbl.state as State,
        charity_tbl.city as city,
        states_tbl.name as state,
        user_tbl.name as name,
        user_tbl.id as admin_id,
        organization_tbl.date_created as date_created,
        organization_tbl.web_url as web_url,
        organization_tbl.title as title,
        organization_tbl.profile_pic_url as profile_pic_url,
        entity_tbl.id as entity_id,
        entity_tbl.slug as userSlug,
        countries_currency.currency_code,
        countries_currency.currency_symbol,
        countries_tbl.country_code
        from charity_admin_tbl
        inner join charity_tbl on charity_tbl.id = charity_admin_tbl.charity_id
        inner join organization_tbl on organization_tbl.id = charity_tbl.organization_id
        inner join entity_tbl on entity_tbl.entity_id = charity_tbl.id and entity_tbl.entity_type ='charity'
        inner join user_tbl on user_tbl.id = charity_admin_tbl.user_id
        left outer join states_tbl on states_tbl.id = charity_tbl.state
        left outer join countries_currency on countries_currency.country_id = charity_tbl.country
        left outer join countries_tbl on countries_tbl.id = charity_tbl.country
        where charity_admin_tbl.charity_id=? and charity_admin_tbl.user_id=? and charity_admin_tbl.date_deleted IS NULL]]>
    </sql-query>
    <sql-query id="adminUsersByCharity">
        <![CDATA[SELECT charity_admin_tbl.id AS id,charity_admin_tbl.can_post AS can_post,
        charity_admin_tbl.can_update_financial AS can_update_financial,
        charity_admin_tbl.can_code AS can_code,
        charity_admin_tbl.can_manage_followers AS can_manage_followers,
        charity_admin_tbl.can_admin AS can_admin,
        charity_admin_tbl.can_view_reports AS can_view_reports,
        charity_admin_tbl.user_id AS user_id,
        charity_admin_tbl.default_value AS default_value,
        user_tbl.name AS name,
        user_profile_tbl.profile_pic_url
        FROM charity_admin_tbl, user_tbl,user_profile_tbl
        WHERE charity_admin_tbl.charity_id=?
        AND charity_admin_tbl.date_deleted IS NULL
        AND user_tbl.id=charity_admin_tbl.user_id
        AND user_tbl.id=user_profile_tbl.user_id
        AND charity_admin_tbl.user_id!=?
        ORDER BY user_tbl.name ASC]]>
    </sql-query>
    <sql-query id="addCharityAdmin">
        <![CDATA[INSERT INTO charity_admin_tbl (charity_id, user_id, can_post, can_update_financial, can_request_withdrawal,can_view_reports, can_code, can_manage_followers, can_admin,default_value) VALUES (?,?,?,?,?,?,?,?,?,?)]]>
    </sql-query>
    <sql-query id="removeAdminUserByCharity">
        <![CDATA[UPDATE charity_admin_tbl SET date_deleted=? WHERE user_id=? and charity_id=?]]>
    </sql-query>
    <sql-query id="getCharitydefault">
        <![CDATA[select * from charity_admin_tbl where charity_id=? and default_value=?]]>
    </sql-query>
    <sql-query id="updatedefaultusermain">
        <![CDATA[UPDATE charity_admin_tbl SET default_value=0 WHERE user_id=?]]>
    </sql-query>
    <sql-query id="updatedefaultuserset">
        <![CDATA[UPDATE charity_admin_tbl SET default_value=1 WHERE user_id=?]]>
    </sql-query>
    <sql-query id="addNewAdmin">
        <![CDATA[INSERT INTO user_tbl (email,name,verification_key) VALUES (?,?,?)]]>
    </sql-query>
    <sql-query id="addProfilePic">
        <![CDATA[INSERT INTO user_profile_tbl (user_id) VALUES (?)]]>
    </sql-query>
    <sql-query id="updateCharityAdmin">
        <![CDATA[UPDATE charity_admin_tbl
        SET can_post=?,can_update_financial=?,can_request_withdrawal=?,can_view_reports=?,can_code=?,can_manage_followers=?,can_admin=? WHERE charity_id=? AND user_id=?]]>
    </sql-query>
    <!--<sql-query id="login_sql">
    <![CDATA[SELECT * FROM user_tbl u INNER JOIN user_profile_tbl up ON up.user_id = u.id
    INNER JOIN charity_admin_tbl ca ON ca.user_id = u.id
    INNER JOIN charity_tbl c ON c.id = ca.charity_id
    WHERE u.email =? and u.password=?]]>
    </sql-query> -->
    <sql-query id="charity_stats">
        <![CDATA[INSERT INTO news]]>
    </sql-query>
    <sql-query id="codeCategoryByCharity">
        <![CDATA[SELECT * FROM code_category_tbl WHERE charity_id=? ORDER BY title ASC]]>
    </sql-query>
    <sql-query id="codeCategoryInsert">
        <![CDATA[INSERT INTO code_category_tbl(charity_id,title) VALUES(?,?)]]>
    </sql-query>
    <sql-query id="followerByCharity">
        <!-- Complete details for follower cards on organization profile pages -->
        <![CDATA[SELECT COALESCE(iq.user_id,false) as is_following,e.entity_id as charity_id,
        e.entity_id as id,
        e.id as entity_id,
        f.user_id as user_id,
        u.name as display_name,
        up.profile_pic_url as profile_pic_url,
        up.background_pic_url,
        up.city as city,
        stl.name as state,
        (select eee.following_users + eee.following_charities + eee.following_codes from entity_tbl eee
        where eee.entity_id=u.id and eee.entity_type='user') as following,
        (select nooffollowers from entity_tbl eee where eee.entity_id=u.id and eee.entity_type='user') as nooffollowers,
        (select count(*) from code_tbl c where c.user_id =u.id and c.individual is not null and c.status!='draft') as campaigns,
        up.about_me as description,
        (select slug as userSlug from entity_tbl eee where eee.entity_id=u.id and eee.entity_type='user') as userSlug
        FROM entity_tbl e inner join follow_tbl f on f.entity_id=e.id AND e.entity_type='charity'
        inner join user_tbl u on u.id=f.user_id and u.date_deleted is NULL
        inner join user_profile_tbl up on up.user_id=u.id
        left outer join (select ff.user_id,ee.entity_id from follow_tbl ff inner join entity_tbl ee  on ff.user_id=? and ff.entity_id=ee.id and ee.entity_type='user') iq on iq.entity_id=u.id
        left outer join states_tbl stl on stl.id = up.state
        WHERE e.entity_id=?
        ORDER BY u.name ASC]]>
    </sql-query>
    <sql-query id="followerByCharityNoStatus">
        <![CDATA[SELECT e.entity_id as charity_id,
        e.id as entity_id,
        et.nooffollowers as 'followers',
        et.noofposts as 'post',
        et.slug as 'slug',
        (et.following_users+et.following_charities+et.following_codes) as 'following',
        (select count(*) as count from code_tbl c where c.user_id=u.id and c.status='published' and c.date_deleted is NULL and c.end_date >= CURDATE()) as campaigns,
        f.user_id as user_id,
        u.name as display_name,
        up.profile_pic_url as profile_pic_url,
        up.background_pic_url,
        up.city as city,
        st.name as state,
        up.about_me as description
        FROM entity_tbl e
        inner join follow_tbl f on f.entity_id=e.id AND e.entity_type='charity'
        inner join user_tbl u on u.id=f.user_id and u.date_deleted is NULL
        inner join entity_tbl et on u.id=et.entity_id AND et.entity_type='user'
        inner join user_profile_tbl up on up.user_id=u.id
        left outer join states_tbl st on st.id = up.state
        WHERE e.entity_id=?
        ORDER BY u.name ASC]]>
    </sql-query>
    <sql-query id="followerByCharityStatus">
        <![CDATA[SELECT e.entity_id as charity_id,
        e.id as entity_id,e.entity_type as entity_type,
       et.nooffollowers as 'followers',
       et.noofposts as 'post',
       et.slug as slug,
       (et.following_users+et.following_charities+et.following_codes) as 'following',
       (select count(*) from code_tbl c where c.user_id =u.id and c.individual is not null and c.status!='draft') as campaigns,
        f.user_id as user_id,
        u.name as display_name,
        up.profile_pic_url as profile_pic_url,
        up.background_pic_url,
        up.city as city,
        st.name as state,
        up.about_me as description,
        COALESCE(null,'user') as entity_type
        FROM entity_tbl e
       inner join follow_tbl f on f.entity_id=e.id AND e.entity_type='charity'
       inner join user_tbl u on u.id=f.user_id
       inner join entity_tbl et on u.id=et.entity_id AND et.entity_type='user'
       inner join user_profile_tbl up on up.user_id=u.id
       left outer join states_tbl st on st.id = up.state
       WHERE e.entity_id=? and u.name like ?
        ORDER BY u.name ASC]]>
    </sql-query>
    <sql-query id="codeCategoryDelete">
        <![CDATA[DELETE FROM code_category_tbl WHERE id = ?]]>
    </sql-query>
    <sql-query id="codeInsert">
        <![CDATA[INSERT INTO code_tbl(parent_code_id, charity_id, category_id, user_id, date_created, date_deleted, code_text, type, start_date, end_date, suggested_donation, title, description, goal, goal_notified, match_amount, match_name, city, state, beneficiary, country, campaign_zip, address_2, address_1, code_picture_url, code_slug, charity_default, short_name, code_video_url, status, last_modified_date, thank_message, fundraise, individual, parent_id, team_campaign, parent_user_id, payment_gateway_id, show_in_search,progress_notifications,can_mailing_required,group_admin,
        last_change_user,donation_alert_required,p2p_approval_required,p2p_offlinedonation_deny,donotallow_p2p_campaigns,published_date,team_approve,team_offline_deny,donotallow_team_campaigns,app_fee) VALUES(?,?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?,?,?,?,?,?,?,?,?,?,?,?)]]>
    </sql-query>
    <!-- Create a new campaign (also includes peer-to-peer campaigns) -->
    <sql-query id="defaultCodeInsert">
        <![CDATA[INSERT INTO code_tbl SET ?]]>
    </sql-query>
    <sql-query id="codesOfCharity">
        <![CDATA[SELECT id, code_text FROM code_tbl WHERE charity_id=? ORDER BY code_text ASC]]>
    </sql-query>
    <sql-query id="codeUrls">
        <![CDATA[SELECT code_text,title,user_id,parent_user_id FROM code_tbl WHERE id=?]]>
    </sql-query>
    <sql-query id="profileByCharity">
        <![CDATA[SELECT charity_tbl.organization_id as organization_id,
        charity_tbl.email as email,
        charity_tbl.phone as phone,
        charity_tbl.reach as reach,
        charity_tbl.ein as tax_id,
        charity_tbl.address_1 as address_1,
        charity_tbl.address_2 as address_2,
        charity_tbl.city as city,
        charity_tbl.state as state,
        charity_tbl.country,
        charity_tbl.postal_code as postal_code,
        charity_tbl.ntee_code as code_registry,
        charity_tbl.charity_from,
        organization_tbl.title as title,
        organization_tbl.full_description as full_description,
        organization_tbl.web_url as web_url,
        organization_tbl.profile_pic_thumb_url as profile_pic_thumb_url,
        organization_tbl.profile_pic_url as profile_pic_url,
        organization_tbl.background_pic_url as background_pic_url,
        organization_tbl.timezone_id as timezone_id,
        et.slug
        FROM charity_tbl
        inner join organization_tbl on organization_tbl.id = charity_tbl.organization_id
        inner join entity_tbl et on charity_tbl.id = et.entity_id and et.entity_type ='charity'
        WHERE charity_tbl.id=?
        ORDER BY organization_tbl.title ASC]]>
    </sql-query>
    <sql-query id="updateCharityProfile">
        <![CDATA[UPDATE charity_tbl SET  reach=?,ein=?, ntee_code=? WHERE id=?]]>
    </sql-query>
    <sql-query id="updateAppFee">
        <![CDATA[UPDATE code_tbl SET  app_fee=? WHERE id=?]]>
    </sql-query>
    <sql-query id="charityInfoUpdate">
        <![CDATA[UPDATE charity_tbl SET email=?,address_1=?,address_2=?,city=?,country=?,state=?,postal_code=?,phone=? WHERE id=?]]>
    </sql-query>
    <sql-query id="charitytable">
        <![CDATA[SELECT organization_id FROM charity_tbl WHERE id=?]]>
    </sql-query>
    <sql-query id="updateCharityProfileInOrg">
        <![CDATA[UPDATE organization_tbl SET title=?,full_description=?,web_url=?,profile_pic_url=?,background_pic_url=?,timezone_id=? WHERE id=?]]>
    </sql-query>
    <sql-query id="profilePicUrlUpdate">
        <![CDATA[UPDATE organization_tbl SET profile_pic_url=?,profile_pic_thumb_url=? WHERE id=?]]>
    </sql-query>
    <sql-query id="charityCodes">
        <![CDATA[SELECT * FROM code_tbl WHERE charity_id=? ORDER BY title ASC]]>
    </sql-query>
    <sql-query id="charityCodeData">
        <![CDATA[SELECT c.*,e.slug,cc.currency_code,cc.currency_symbol,cat.category_id FROM code_tbl c
        inner join entity_tbl e on e.entity_id= c.id and e.entity_type='code'
        inner join charity_tbl ct on ct.id= c.charity_id
        inner join ww_code_category_tbl cat on cat.code_id= c.id
        left outer join countries_currency cc on cc.country_id = ct.country
        WHERE c.id=?]]>
    </sql-query>
    <sql-query id="updateCharityCodeData">
        <![CDATA[UPDATE code_tbl SET code_text=?,end_date=?,suggested_donation=?,title=?,code_picture_url=?, code_video_url=?, description=?, type=?, goal=?, match_amount=?, match_name=?, category_id=?, city=?, state=?, campaign_zip=?,address_1=?,address_2=?,short_name=?,country=?,thank_message=?,beneficiary=?,category_id=?,last_change_user=?,last_modified_date=?,can_mailing_required=?,p2p_approval_required=?,donation_alert_required=?,p2p_offlinedonation_deny=? WHERE id=?]]>
    </sql-query>
    <sql-query id="charityTransactions">
        <![CDATA[SELECT transaction_tbl.id as transaction_id,
        UNIX_TIMESTAMP(transaction_tbl.transaction_date) AS transaction_date,
        transaction_tbl.amount as amount,
        transaction_tbl.code_id as code_id,
        transaction_tbl.source as source,
        transaction_tbl.user_id as user_id,
        transaction_tbl.type as transaction_type,
        transaction_tbl.processing_fee as processing_fee,
        transaction_tbl.wonderwe_fee as wonderwe_fee,
        transaction_tbl.refunded_date as refunded_date,
        transaction_tbl.refunded_amount as refunded_amount,
        user_tbl.name as name,
        user_tbl.id as user_id
        FROM transaction_tbl, user_tbl
        WHERE transaction_tbl.charity_id=?
        AND transaction_tbl.transaction_date >= ?
        AND transaction_tbl.transaction_date <= ?
        AND user_tbl.id=transaction_tbl.user_id
        ORDER BY transaction_tbl.transaction_date DESC]]>
    </sql-query>
    <sql-query id="charityCodeTransactions">
        <![CDATA[SELECT transaction_tbl.id as transaction_id,
        UNIX_TIMESTAMP(transaction_tbl.transaction_date) AS transaction_date,
        transaction_tbl.amount as amount,
        transaction_tbl.code_id as code_id,
        transaction_tbl.source as source,
        transaction_tbl.user_id as user_id,
        transaction_tbl.type as transaction_type,
        transaction_tbl.processing_fee as processing_fee,
        transaction_tbl.wonderwe_fee as wonderwe_fee,
        transaction_tbl.refunded_date as refunded_date,
        transaction_tbl.refunded_amount as refunded_amount,
        code_tbl.code_text as code_text,
        user_tbl.name as name,
        user_tbl.id as user_id
        FROM transaction_tbl, code_tbl, user_tbl
        WHERE transaction_tbl.charity_id=?
        AND transaction_tbl.transaction_date >= ?
        AND transaction_tbl.transaction_date <= ?
        AND transaction_tbl.type='code'
        AND code_tbl.id=transaction_tbl.code_id
        AND user_tbl.id=transaction_tbl.user_id
        ORDER BY transaction_tbl.transaction_date DESC]]>
    </sql-query>
    <sql-query id="charityStatistics">
        <![CDATA[SELECT DATE(tt.transaction_date) 'date', cdt.title 'campaign', tt.amount 'amount', ut.name 'donor'
        FROM transaction_tbl tt, user_tbl ut, code_tbl cdt
        WHERE tt.charity_id=?
        AND tt.user_id = ut.id
        AND tt.code_id = cdt.id
union all
SELECT DATE(tt.transaction_date) 'date', cht.name_tmp 'campaign', tt.amount 'amount', ut.name 'donor'
 FROM transaction_tbl tt
inner join charity_tbl cht on cht.id=tt.charity_id and tt.code_id is null
inner join user_tbl ut on ut.id=tt.user_id where tt.charity_id=? order by date desc
]]>
    </sql-query>
    <sql-query id="selectCharityCategories">
        <![CDATA[SELECT category_id, charity_id FROM ww_charity_category_tbl WHERE charity_id=?]]>
    </sql-query>
    <sql-query id="getCategoryTitle">
        <![CDATA[SELECT title FROM charity_category_tbl WHERE id=?]]>
    </sql-query>
    <!-- update organization categories from organization profile settings page -->
    <sql-query id="addSelectCategorys">
        <![CDATA[INSERT INTO ww_charity_category_tbl (category_id,charity_id) VALUES (?,?)]]>
    </sql-query>
    <!-- Load existing member data in member portal settings page -->
    <sql-query id="profileinfo">
        <![CDATA[select u.*,up.*,e.slug from user_tbl u
                          INNER JOIN user_profile_tbl up on up.user_id =u.id
                          inner join entity_tbl e on e.entity_id = u.id and e.entity_type ='user'
                          where u.id=?]]>
    </sql-query>
    <sql-query id="profileinfoWithEmail">
        <![CDATA[select * from user_tbl u INNER JOIN user_profile_tbl up on up.user_id =u.id where u.email=?]]>
    </sql-query>
    <sql-query id="orgname">
        <![CDATA[SELECT title,web_url FROM organization_tbl WHERE id=?]]>
    </sql-query>
    <sql-query id="updatemail">
        <![CDATA[UPDATE user_tbl SET email=? WHERE id=?]]>
    </sql-query>
    <sql-query id="charity_count">
        <![CDATA[SELECT charity_admin_tbl.charity_id AS id
        FROM charity_admin_tbl
        WHERE charity_admin_tbl.user_id=?
        AND charity_admin_tbl.date_deleted IS NULL]]>
    </sql-query>
    <sql-query id="transFilterByDates">
        <![CDATA[SELECT   tt.transaction_date, SUM(tt.amount) 'Total_Filter_AS'
        FROM     transaction_tbl tt
        WHERE    tt.charity_id = ?
        AND (tt.transaction_date BETWEEN ? and ?)
        ##AND YEAR(tt.transaction_date)=2015
        GROUP BY YEAR(tt.transaction_date)
        ORDER BY YEAR(transaction_date) DESC]]>
    </sql-query>
    <sql-query id="transFilterByYear">
        <![CDATA[SELECT  SUM(tt.amount) 'as_donations_yearly',
        COUNT(DISTINCT(tt.user_id)) 'as_donors_yearly'
        FROM transaction_tbl tt
        WHERE tt.charity_id = ?
        AND tt.transaction_date BETWEEN CURDATE() - INTERVAL 1 YEAR AND CURDATE()
        GROUP BY DATE_FORMAT(tt.transaction_date,'%y')
        ORDER BY DATE_FORMAT(tt.transaction_date,'%y') DESC]]>
    </sql-query>
    <sql-query id="transFilterByMonth">
        <![CDATA[SELECT  SUM(tt.amount) 'as_donations_montly',
        COUNT(DISTINCT(tt.user_id)) 'as_donors_montly'
        FROM transaction_tbl tt
        WHERE tt.charity_id = ?
        AND tt.transaction_date BETWEEN CURDATE() - INTERVAL 2 MONTH AND CURDATE()
        GROUP BY DATE_FORMAT(tt.transaction_date,'%y%m')
        ORDER BY DATE_FORMAT(tt.transaction_date,'%y%m') DESC
        ]]>
    </sql-query>
    <sql-query id="transFilterByWeek">
        <![CDATA[SELECT SUM(tt.amount) 'as_donations_weekly',
        COUNT(DISTINCT(tt.user_id)) 'as_donors_weekly'
        FROM transaction_tbl tt
        WHERE tt.charity_id = 1500337
        AND tt.transaction_date BETWEEN CURDATE() - INTERVAL 1 WEEK AND CURDATE()
        GROUP BY WEEK(tt.transaction_date)
        ORDER BY WEEK(tt.transaction_date) DESC
        ]]>
    </sql-query>
    <sql-query id="transFilterByToday">
        <![CDATA[SELECT  SUM(tt.amount) 'as_donations_day',
        COUNT(DISTINCT(tt.user_id)) 'as_donors_day'